#Location of the keystore and keystore properties. \nEnvironment variables `ks=/some/path` and `ksp=/some/path` are going to take precedence
#Fri, 22 Sep 2023 15:15:48 -0500

ks=/home/sisinfo
ksp=/home/sisinfo
